name: Deploy to Endora (Cars)

on:
  push:
    branches: [master]
    paths:
      - "Cars_FrontendReact/**"
      - "Cars-BackendPHP/**"
      - ".github/workflows/deploy.yml"

concurrency:
  group: deploy-endora
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FRONTEND_DIR: Cars_FrontendReact
      BACKEND_DIR: Cars-BackendPHP
      OUT_DIR: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Build React (Vite)
        working-directory: ${{ env.FRONTEND_DIR }}
        # pokud nasazuješ do /Cars/ podadresáře a potřebuješ base,
        # odkomentuj následující env a ve vite.config.js měj base: process.env.VITE_BASE ?? '/'
        # env:
        #   VITE_BASE: /Cars/
        run: |
          npm ci
          npm run build

      - name: Prepare deploy folder
        run: |
          rm -rf "$OUT_DIR" && mkdir -p "$OUT_DIR/Cars-BackendPHP"

          # Frontend -> kořen deploy balíčku
          BUILD_DIR="$FRONTEND_DIR/dist"; if [ ! -d "$BUILD_DIR" ]; then BUILD_DIR="$FRONTEND_DIR/build"; fi
          rsync -a "$BUILD_DIR"/ "$OUT_DIR"/

          # Backend -> /Cars-BackendPHP (bez login.php)
          rsync -a --exclude 'login.php' "$BACKEND_DIR"/ "$OUT_DIR/Cars-BackendPHP"/

          # Root .htaccess – přepiš /api/* na /Cars-BackendPHP/*, zbytek je SPA
          printf '%s\n' \
            'RewriteEngine On' \
            '' \
            '# existující soubory/složky' \
            'RewriteCond %{REQUEST_FILENAME} -f [OR]' \
            'RewriteCond %{REQUEST_FILENAME} -d' \
            'RewriteRule ^ - [L]' \
            '' \
            '# /api/* -> /Cars-BackendPHP/*' \
            'RewriteRule ^api/(.*)$ /Cars-BackendPHP/$1 [L]' \
            '' \
            '# přímé volání .php nech být' \
            'RewriteCond %{REQUEST_URI} \.php$ [NC]' \
            'RewriteRule ^ - [L]' \
            '' \
            '# SPA fallback' \
            'RewriteRule . /index.html [L]' \
            > "$OUT_DIR/.htaccess"

      # ====== DEPLOY PŘES LFTP (FTPS) – bez externí akce ======
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload via lftp (FTPS)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: ${{ secrets.FTP_DIR }}Cars/
          LOCAL_DIR: ${{ env.OUT_DIR }}/
        run: |
          lftp -e "
            set ftp:passive-mode on;
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate false;
            set net:max-retries 2;
            set net:timeout 30;
            open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER};
            mkdir -p ${REMOTE_DIR};
            mirror -Rnv ${LOCAL_DIR} ${REMOTE_DIR} \
              --exclude-glob .git* \
              --exclude-glob node_modules \
              --exclude-glob .github \
              --exclude-glob tests;
            bye
          "
